apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: fullstack-app
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm1haGFyamFuMTE=
  MONGO_INITDB_ROOT_PASSWORD: cXdlcnR5dWlvcEAxMjM0NQ==
