apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  namespace: fullstack-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: rujalmhn/project-node:v1.1
          envFrom:
            - configMapRef:
                name: node-config
          ports:
            - containerPort: 3000
          env:
          - name: MONGO_URI
            value: mongodb://mongodb:27017/mydb