apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: fullstack-app
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mongodb
  storageClassName: manual