apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: fullstack-app
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: node-app
  type: ClusterIP
